# Generated by Django 2.2 on 2022-05-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220506_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='lastname',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
