# Generated by Django 4.0.3 on 2022-05-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220510_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
