# Generated by Django 2.2 on 2022-03-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_prdct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catag',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
