# Generated by Django 2.2 on 2022-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20220329_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdct',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
