# Generated by Django 2.2 on 2022-04-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20220411_1346'),
        ('homeapp', '0004_prdct_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catag',
            new_name='categ',
        ),
        migrations.RenameModel(
            old_name='prdct',
            new_name='products',
        ),
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
