# Generated by Django 2.2 on 2022-04-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_auto_20220412_1340'),
        ('homeapp', '0005_auto_20220411_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
