# Generated by Django 2.2 on 2022-04-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
