# Generated by Django 2.2 on 2022-04-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='product',
            new_name='prodt',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='qunty',
            new_name='quan',
        ),
    ]
