# Generated by Django 2.2 on 2022-04-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20220411_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='items',
            name='prodt',
        ),
        migrations.DeleteModel(
            name='cartlist',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
