# Generated by Django 2.2 on 2022-04-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quan',
            new_name='quantity',
        ),
    ]
